version: "3.7"

services:
  app:
    build:
      context: .
    command: daphne djdoodle.asgi:application -u /usr/src/app/daphne.sock
    volumes:
      - $PWD:/usr/src/app

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD:/usr/src/app
